name: Check & Release

on:
    push:
        branches:
            - master

jobs:
    # NPM install is done in a separate job and cached to speed up the following jobs.
    build_and_test:
        name: Build & Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [ 12, 14, 15, 16 ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   name: Run Tests
                run: npm test

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 14
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   run: npm run build

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 14
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   run: npm run lint

    # The deploy job is long but there are only 2 important parts. NPM publish
    # and triggering of docker image builds in the apify-actor-docker repo.
    deploy:
        name: Publish to NPM
        needs: [ build_and_test ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v1
                with:
                    node-version: 16
                    registry-url: https://registry.npmjs.org/
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Release
                run: npm run release
