name: Check & Release

on:
    push:
        branches:
            - master

jobs:
    test:
        name: Test
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [ 12, 14, 15, 16 ]

        steps:
            -   uses: actions/checkout@v2
                with:
                    fetch-depth: 0 # we need to pull everything to allow lerna to detect what packages changed
                    ref: master
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   name: Run Tests
                run: npm test

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 16
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   run: npm run build

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js 16
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install Dependencies
                run: npm install
            -   run: npm run lint

    deploy:
        name: Publish to NPM
        needs: [ test, build, lint ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GH_TOKEN }}
            -   uses: actions/setup-node@v1
                with:
                    node-version: 16
                    registry-url: https://registry.npmjs.org/
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Release
                run: |
                    git config --global user.name 'Apify Release Bot'
                    git config --global user.email 'noreply@apify.com'
                    echo "access=public" >> .npmrc
                    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
                    npm install
                    git status
                    git diff
                    npm run build
                    git status
                    git diff
                    git stash save
                    git status
                    git diff
                    echo 'stashed'
                    npx lerna version patch --yes --no-push
                    echo 'versioned'
                    git status
                    git diff
                    git stash pop
                    echo 'unstashed'
                    git status
                    git diff
                    git commit -a --amend --no-edit
                    echo 'amended'
                    git push --follow-tags
                    echo 'pushed'
                    npx lerna publish from-package --contents dist --yes --no-verify-access
                    echo 'published'
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                    GIT_USER: "noreply@apify.com:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
